export const metadata = {
    title: "SoftyCraft || Service",
    description: "Generated by create next app",
  };

const service = () => {
    return (
        <div>
            
        </div>
    );
};

export default service;