export const metadata = {
    title: "SoftyCraft || Contact",
    description: "Generated by create next app",
  };
const contact = () => {
    return (
        <div>
            <h2>Contact</h2>
        </div>
    );
};

export default contact;