import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Component/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SoftyCraft',
  description: 'Generated by SoftyCraft',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
