export const metadata = {
    title: "SoftyCraft || Blog",
    description: "Generated by create next app",
  };
const blog = () => {
    return (
        <div>
            <h2>Blog</h2>
            
        </div>
    );
};          

export default blog;